name: Test
on: [push, pull_request]
jobs:
  test:
    name: ${{ matrix.lang }} tests on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        lang: [Python]

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: '3.7'

    - name: Install Python 3.x dependencies
      run: |
        python3 -m pip install --upgrade pip setuptools wheel
        python3 -m pip install -e .[test]
    
    - name: Set up R 3.6
      if: matrix.lang == 'R'
      uses: r-lib/actions/setup-r@v1
      with:
        r-version: '3.6.3' 
    
    - name: Install R 3.6 system dependencies
      if: matrix.lang == 'R' && matrix.os == 'ubuntu-latest'
      run: sudo apt-get update; sudo apt-get install -y libcurl4-openssl-dev qpdf libgit2-dev

    - name: Install R 3.6 Rlang dependencies
      if: matrix.lang == 'R'
      run: |
        python3 -m pip install . 
        Rscript -e 'install.packages("devtools", repos="https://cloud.r-project.org", Ncpus=8)'
        Rscript -e 'devtools::install_deps("R", dependencies=TRUE, repos="https://cloud.r-project.org", upgrade="default")'
        R CMD INSTALL R
        Rscript -e 'install.packages(c("data.table", "caret", "glmnet", "Matrix", "rjson"), repos="https://cloud.r-project.org", Ncpus=8)'   

    - name: Execute R tests
      if: matrix.lang == 'R'
      run: |
        cd R/tests
        Rscript run_tests.R

    - name: Execute Python tests
      if: matrix.lang == 'python'
      run: tox

    - name: Execute pytest tests
      if: matrix.lang == 'python'
      run: pytest
